### PR TITLE
fix: gracefully handle race condition between parallel builds

### PR DESCRIPTION
**Pull request by levibostian**
I am receiving build failures when I run 2 parallel builds that both run setup-mint when they startup. You can reproduce this scenario by creating 2 workflows that get triggered when a PR is opened and both workflows run setup-mint action. 1 will succeed with saving the cache, the other will fail early and give error message "Unable to reserve cache with key -macOS-X64-irgaly/setup-mint-master, another job may be creating this cache."

I believe this is a race condition between the parallel builds where they both attempt to reserve the github actions cache using the same cache key. One way to handle this scenario is to not fail the action when this race condition occurs, since you only need 1 of the parallel builds to save the cache. The other build can skip saving and move on.

References:
https://github.com/oven-sh/setup-bun/issues/45 - experiencing the same issue as this person https://github.com/actions/cache/issues/485#issuecomment-744145040 - explaining the idea of how caches are reserved

### CODE REVIEW

**Comment by levibostian** [comment]
Converting to draft PR while I finish testing. I am running the fork against a project of mine to see if this fixes the problem I was experiencing.

**Comment by levibostian** [comment]
Testing concluded and successful! 

# How I tested 

* I have 2 github action jobs. Both jobs run in parallel when a PR is opened and both run the setup-mint action first. 
* I modified my github workflows to run this PR's fix. 
* I clear all github actions caches. 
* I open a PR which runs the 2 github jobs in parallel. 
* The github jobs both compile `mint` and both run `mint bootstrap` for the first time. When it's time for the jobs to save the cache, you will notice that [1 of the jobs will display a warning but will continue running](https://github.com/levibostian/Wendy-iOS/actions/runs/8538446435/job/23392320708?pr=140#step:3:371). The [other job will successfully save the cache](https://github.com/levibostian/Wendy-iOS/actions/runs/8538446435/job/23392320376?pr=140#step:3:372). 

* After the 2 jobs finish running successfully for the first time (and successfully saving a cache for the first time), I re-ran the jobs to see if they restore the caches successfully. Both of the 2 jobs successfully restore the previous cache and both run bootstrap using this cache. The 2 runners run super fast now! [1 job](https://github.com/levibostian/Wendy-iOS/actions/runs/8538446435/job/23393016864?pr=140#step:3:41), [2nd job](https://github.com/levibostian/Wendy-iOS/actions/runs/8538446435/job/23393017203?pr=140#step:3:41). 

---

Re-opening PR since testing is successful. Ready for review.

**Comment by irgaly** [comment]
@levibostian 
Thank you for your report and careful testing!
It seems a nice approach to key conflict.

I'll merge this and release new one.

**Comment by irgaly** [comment]
I published [v1.4.0](https://github.com/irgaly/setup-mint/releases/tag/v1.4.0) with this PR's fix. Please check it with `irgaly/setup-mint@v1` that is automatically point v1.4.0.
Thanks!

**Pull request merged**
