### PR TITLE
Update cache for MINT_PATH and MINT_LINK_PATH

### PR DESCRIPTION
**Pull request by Wei18**
- base on #25

### CODE REVIEW

**Comment by irgaly** [comment]
Thank you for your PR!

in #25, I have changed mint executable binary to `$HOME/bin/mint` from `/usr/local/bin/mint`.
Then that mint executable binary will be stored to cache by `mintPaths` and `mintCacheKey`.

https://github.com/irgaly/setup-mint/blob/8e4c5f79f0f12ae8a2ef89e69371c5fe93b2c5e4/src/main.ts#L71-L77

On the other hand, mintBinaryDirectory is `~/.mint/bin`, this directory is used to putting SwiftPM command (xcodegen, swiftgen...) that was built by mint.

Because the mint binary itself is stored to `$HOME/bin/mint` and cached independently, so It's not affected by `MINT_PATH` or  `MINT_LINK_PATH`.

Sorry these variable names is confusable in my code. GitHub Actions test result seems store / restore mint binary correctly.

https://github.com/irgaly/setup-mint/actions/runs/9816733619/job/27202672853

> mint cache key: -macOS-ARM64-irgaly/setup-mint-0.17.0
> Cache Size: ~1 MB (698706 B)
> /opt/homebrew/bin/gtar -xf /Users/runner/work/_temp/92b1c20c-d55f-4[14](https://github.com/irgaly/setup-mint/actions/runs/9816733619/job/27202672853#step:3:15)f-a7ce-70645f0356f1/cache.tzst -P -C /Users/runner/work/setup-mint/setup-mint --delay-directory-restore --use-compress-program unzstd
> Cache restored successfully
> /Users/runner/bin/mint restored from cache

**Comment by Wei18** [comment]
I hit the issue when uses irgaly/setup-mint.
```
~/.mint/bin/mint // default behavior not found, 
$HOME/bin/mint // PASS
```
I believe the variable `MINT_BIN = $MINT_LINK_PATH/mint` is used everywhere...

**Comment by irgaly** [comment]
I want to hear what usecase do you have, and what problem you faced?

---

https://github.com/yonaskolb/Mint

The mint binary is default to installed to `/usr/local/bin/mint` for Homebrew.

image

Or for `make install`.

https://github.com/yonaskolb/Mint/blob/7b55208b2609e590303a3c498372b72b3b7b4c03/Makefile#L5-L6

image

`~/.mint/bin/mint` is default for `mint install`.

image

**Comment by Wei18** [comment]
> ~/.mint/bin/mint is default for mint install.

Our developers use this path on local side,
so I hit the error `mint not found` when running  after setup-mint@1.5.0 on GitHub actions.

Good to know, there are 2 paths between homebrew and mint itself..

**Comment by Wei18** [comment]
- Close this and refer to #28

**Comment by irgaly** [comment]
@Wei18 

I released v1.6.0, and setup-mint@v1 automatically point this new version. Please check this.

https://github.com/irgaly/setup-mint/releases/tag/v1.6.0

v1.6.0 now, setup-mint will run `mint bootstrap --link`, so swift command symbolic link is placed in `~/.mint/bin/{executable}`.
Also you can specify `mint-executable-directory: ~/.mint/bin` with your self hosted macOS runner, this option will prevent instllation error.

**Pull request closed without merging**
